theme: jekyll-theme-giellalt
title: Dictionary for Hungarian ⇒ Udmurt
description: An electronic dictionary from Hungarian to Udmurt

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
